language: cpp

matrix:
  include:
    - dist: xenial
      compiler: clang
      before_install:
          - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
          - sudo apt-get -qy update
      install:
          - sudo apt-get -qy install  qt512svg qt512base qt512translations  qt512tools mesa-common-dev libglu1-mesa-dev freeglut3-dev

    - os: osx
      osx_image: xcode10
      before_install:
          - brew update
      install:
          - brew install cppcheck
          - brew install qt5
          - brew link --force qt && ln -s /usr/local/Cellar/qt/5.13.0/mkspecs /usr/local/mkspecs && ln -s /usr/local/Cellar/qt/5.13.0/plugins /usr/local/plugins
      #env:
        #- CMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.13.0
        #- PATH=/usr/local/opt/qt5/bin:$PATH

script:
    - mkdir -p build
    - pushd build
    - cmake ../ && make -j4 && env CTEST_OUTPUT_ON_FAILURE=1 make test
    - popd
